### PR TITLE
version 0.2.1

### PR DESCRIPTION
**Pull request by debris**
@maciejhirsz please review. If it's ok and we do not need major version bump, I'll release a new version to crates.io

### CODE REVIEW

**Comment by tomusdrw** [comment]
I think the external API has changed, might be better to bump `minor `version.

**Comment by maciejhirsz** [comment]
Yeah, the API surface is different, should do a 0.3.

Edit: I've bumped the crate to 0.3.0, bumped the CLI to 0.1.1 (nothing in the way the CLI is used has changed).

**Comment by Weasy666** [comment]
Could you please publish 0.3 to crates.io? That would be really nice.

**Comment by Weasy666** [comment]
Thank you for publishing this. 👍

**Comment by tomusdrw** [comment]
@Weasy666 Pleasure, sorry it took so long!

**Pull request merged**
